---
# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

blank_issues_enabled: false
contact_links:
  - name: "❓ Question"
    url: "../../../discussions/new/choose"
    about: Ask about anything
