---
name: "Auto-doc shell scripts"

on: [push, pull_request, workflow_dispatch]

jobs:
  shdoc:
    name: "shdoc"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
        #with:
          #repository: "micro5k/microg-unofficial-installer"
          #ref: "26a99ae486dd92e3438a4f82e8415bd49336cfd7"
      - name: "Documentation generator"
        uses: a5k-testing/github-doc-test@main
