---
name: "Code linting"

on: [push, pull_request, workflow_dispatch]

jobs:
  coverage:
    name: "Coverage"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
      - name: "Set up Ruby"
        uses: ruby/setup-ruby@v1.83.0
        with:
          ruby-version: "3.0"
          bundler-cache: true
      - name: "Install bashcov"
        shell: bash
        run: |
          # Install bashcov
          gem install bashcov
