---
name: "Code linting (Linux)"

on: [push, pull_request, workflow_dispatch]

jobs:
  shellchecker:
    name: "ShellChecker"
    runs-on: ubuntu-latest
    outputs:
      num-files-wth-issues: ${{ steps.shellchecker-run.outputs.NumFilesWthIssues }}
      list-files-with-issues: ${{ steps.shellchecker-run.outputs.ListFilesWithIssues }}

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
        # with:
          # repository: "micro5k/microg-unofficial-installer"
          # ref: "26a99ae486dd92e3438a4f82e8415bd49336cfd7"
      - uses: actions/upload-artifact@v2
        with:
          name: "Documentation"
          path: "documentation/"
      - name: "ShellChecker"
        id: "shellchecker-run"
        uses: a5k-testing/github-action-test@main
        with:
          # shellcheck-version: "v0.7.2"
          enable-all-opt-checks: "true"
          ignore-files: "gradlew|.gitlab-ci.yml"
      # - name: "REUSE Compliance Check"
        # uses: fsfe/reuse-action@v1

  validator:
    name: "Validate dep5"
    runs-on: ubuntu-latest

    steps:
      - name: "Check out code"
        uses: actions/checkout@v3
      - name: "Validate dep5"
        shell: bash
        run: |
          # Validating dep5
          if ! test -e './.reuse/dep5'; then exit 0; fi
          sudo apt-get -qq -y install cme 1> /dev/null
          cme check dpkg-copyright -file './.reuse/dep5'; status="${?}"
          if test "${status}" -eq 0; then echo 'Pass'; else echo 'Fail'; exit "${status}"; fi

  get-results:
    name: "Get results"
    runs-on: ubuntu-latest
    if: always()
    needs: shellchecker

    steps:
      - name: Display number of files with issues
        shell: bash
        run: |
          # Total:
          count="${{ needs.shellchecker.outputs.num-files-wth-issues }}"
          if test -n "${count?}"; then echo "${count}"; fi
      - name: Display list of files with issues
        shell: bash
        run: |
          # List:
          files_list=${{ needs.shellchecker.outputs.list-files-with-issues }}
          for val in "${files_list[@]?}"; do echo "${val}"; done
