name: Shell Linter

on:
  push:
    branches:
    - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: 'micro5k/microg-unofficial-installer'
          ref: '26a99ae486dd92e3438a4f82e8415bd49336cfd7'
      - name: Run ShellCheck
        uses: a5k-testing/github-action-test@main
        with:
          ignore: 'gradlew.bat|gitlab-ci.yml'
