---
name: SC Linux

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: "micro5k/microg-unofficial-installer"
          #ref: "26a99ae486dd92e3438a4f82e8415bd49336cfd7"
      - name: Run ShellCheck
        id: shellcheck-run
        uses: a5k-testing/github-action-test@main
        with:
          #shellcheck-version: "v0.7.2"
          enable-all-opt-checks: "true"
          ignore-files: "gradlew|.gitlab-ci.yml"

  get-results:
    runs-on: ubuntu-latest
    if: always()
    needs: lint

    steps:
      - name: Display number of files with issues
        run: |
          echo "${{ needs.lint.steps.shellcheck-run.outputs.num-files-wth-issues }}"
      - name: Display path of files with issues
        run: |
          echo "${{ needs.lint.steps.shellcheck-run.outputs.path-files-with-issues }}"
