---
name: "Code linting (Linux)"

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
  workflow_dispatch:

jobs:
  shellchecker:
    name: "ShellChecker"
    runs-on: ubuntu-latest
    outputs:
      num-files-wth-issues: ${{ steps.shellchecker-run.outputs.NumFilesWthIssues }}
      list-files-with-issues: ${{ steps.shellchecker-run.outputs.ListFilesWithIssues }}

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
        # with:
          # repository: "micro5k/microg-unofficial-installer"
          # ref: "26a99ae486dd92e3438a4f82e8415bd49336cfd7"
      - uses: actions/upload-artifact@v3
        with:
          name: "Documentation"
          path: "documentation/"
      - name: "Test"
        id: "my-test"
        shell: bash
        run: |
          text='abc'
          echo "::set-output name=my-test-text::${text}"
      - name: "Test 2"
        id: "my-test2"
        shell: bash
        run: |
          echo "${{ steps.my-test.outputs.my-test-text }}"
      - name: "ShellChecker"
        id: "shellchecker-run"
        uses: a5k-testing/github-action-test@main
        with:
          # shellcheck-version: "v0.7.2"
          enable-all-opt-checks: "true"
          ignore-files: "gradlew|.gitlab-ci.yml|test-123"

  get-results:
    name: "Get results"
    runs-on: ubuntu-latest
    if: always()
    needs: shellchecker

    steps:
      - name: Display number of files with issues
        shell: bash
        run: |
          # Total:
          count="${{ needs.shellchecker.outputs.num-files-wth-issues }}"
          if test -n "${count?}"; then echo "${count}"; fi
      - name: Display list of files with issues
        if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
        shell: bash
        run: |
          # List:
          files_list=${{ needs.shellchecker.outputs.list-files-with-issues }}
          for val in "${files_list[@]?}"; do echo "${val}"; done
