---
name: "Update tags"

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:

jobs:
  tags-updater:
    name: "Update tags"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Update tags"
        uses: bewuethr/release-tracker-action@v1
        with:
          update-latest: true
          update-minor: false
