---
name: Docs

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Action update docs action
        uses: npalm/action-docs-action@develop
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          author: "ale5000 <15793015+ale5000-git@users.noreply.github.com>"
          signoff: "true"
          title: "Auto-update action documentation"
          body: "Automated changes by a [GitHub Action](https://github.com/marketplace/actions/action-update-docs-action)"
          commit-message: "Auto-update action documentation"
          branch: "auto-update-doc/patch"
          delete-branch: "true"
