name: Docs

on:
  push:
    branches:
    - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Action update docs action
        uses: npalm/action-docs-action@v1.1.0
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
         author: 'ale5000 <15793015+ale5000-git@users.noreply.github.com>'
         title: 'Auto-update action documentation'
         commit-message: 'Auto-update action documentation'
