---
name: YAML Lint
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # with:
        #   repository: 'micro5k/microg-unofficial-installer'
      - name: "YAML Lint"
        uses: ibiqlik/action-yamllint@v3
        # with:
        #   format: github
