---
name: YAML Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # with:
          # repository: 'a5k-actions/shellchecker'
      - name: "Validate codecov.yml"
        shell: bash
        run: |
          codecov_path='${{ github.workspace }}/codecov.yml'
          if test -f "${codecov_path}"; then
            wget -O- --post-file "${codecov_path}" https://codecov.io/validate || (echo 'NOT Valid!'; exit 1)
          fi
      - name: "YAML Lint"
        uses: ibiqlik/action-yamllint@v3
        # with:
          # format: github
